### PR TITLE
Adding support for PREEMPT_RT

### PR DESCRIPTION
**Pull request by krisklau**
Hi,

I wanted to test adding the RT patch to the kernel we use in glued, and run some benchmarks with cyclictest to see the difference in latencies. 

By applying the rt patch to 3.14.58 on a beaglebone black, and using the following benchmark command:
    `cyclictest -l1000000 -m -n -a0 -t1 -p99 -i400 -h400 -q`
I got the following:

results

` vanilla:  Total: 001000000 # Min Latencies: 00007 # Avg Latencies: 00009 # Max Latencies: 02934`
`rt-patch:Total: 001000000 # Min Latencies: 00007 # Avg Latencies: 00009 # Max Latencies: 00041`

which I find interesting enough to do some further tests. 

I open this PR to start a discussion on:
 1. Using the rt patch at all, is it necessary? 
 2. If so, find a clever way to incorporate in the build system. 

Attached is a suggestion for 2. As can be seen in https://www.kernel.org/pub/linux/kernel/projects/rt/3.14/, not all releases gets a rt-patch, which gives a couple of drawbacks of the suggested method. This means that if one wants to use the newest vanilla kernel (e.g. 3.14.63), that may not have an rt patch yet, several files needs to be duplicated. (configs, linux-patches, linux-headers? etc). Ideally, I guess the original version could be tracked, and copied from the appropriate locations instead. 

The file  `rules/linux/preempt_rt.bash` keeps track of the kernel version and rt version, and overrides from `default.bash`. Also, some code is duplicated to add functionality to the functions `configure()` and `post_unpack()`, which is not ideal imo. Maybe add some additional hooks in `default.bash`, like `post_configure()`, and `post_unpack_patch()`? (just in the linux-package, called by the appropriate functions in `default.bash`)

Thanks for all inputs, comments and suggestions!

Regards,
Kristian

### CODE REVIEW

**Comment by rasmartins** [comment]
We have used the RT patches in GLUED many years ago. Can you issue separate pull requests, one for the rt-tests (which can be easily merged), one for the kernel, and another for ntnu-b2xx ? Since we are using LTS kernels I guess we can avoid duplicating the patches using only the major and minor versions.

**Comment by krisklau** [comment]
Hi,
Thanks, will do. 

Good idea. Do you reckon we change the paths to 3.14.xx, or a scheme to apply the newest patch? Do you remember why you stopped using the RT patches?

Kristian

**Comment by krisklau** [comment]
For instance something like this: https://github.com/krisklau/glued/commit/414f88aef1d8a0daeec38f0ec63d384990b1075c

**Comment by rasmartins** [comment]
Give me some time to go through this. We stopped using the -rt patches because our hardware was not servicing interrupt requests fast enough thus leading to data loss.

**Comment by rasmartins** [comment]
Take a look at the branch feature/linux-rt. I think this approach should suffice.

**Comment by krisklau** [comment]
Hi,

I really like that approach, nice. Tested and verified. 

Do you know of another mirror for the rt-patches? They seem to move the patches from the main folder https://www.kernel.org/pub/linux/kernel/projects/rt/3.14/ to older/ after each release. 

Kristian

**Comment by rasmartins** [comment]
Hi,

I will mirror the patch used by GLUED in our servers.

**Comment by rasmartins** [comment]
Please re-submit your config files

**Pull request closed without merging**
